#! /usr/local/bin/bash

# Update all timelines for all CUNY colleges of interest.

# Institutions
colleges='BAR BCC BKL BMC CSI CTY HOS HTR JJC KCC LAG LEH MEC NCC NYT QCC QNS SPS YRK'

# The admit term list has to be updated manually.
for admit_term in 1192 1199 1202 1209 1212 1219
do echo $admit_term
   ./timelines.py -i $colleges -a $admit_term
done
