#! /usr/local/bin/bash

rsync -vte ssh chris@trexlabs.lehman.edu:/home/chris/Projects/transfer_timeline/downloads/CV_QNS_* $HOME/Projects/transfer_timeline/downloads
rsync -vte ssh chris@trexlabs.lehman.edu:/home/chris/Projects/transfer_timeline/queries/CV_QNS_* $HOME/Projects/transfer_timeline/queries
